DROP DATABASE IF EXISTS juego;
CREATE DATABASE juego;

USE JUEGO;

CREATE TABLE JUGADOR (
	ID INT NOT NULL,
	USERNAME VARCHAR(60) NOT NULL,
	PASSWORD VARCHAR(60) NOT NULL,
	PRIMARY KEY(ID)
)ENGINE=InnoBD;

CREATE TABLE PARTIDA (
	ID INT NOT NULL,
	FECHA VARCHAR(60),
	DURACION INT,
	GANADOR VARCHAR(60),
	PRIMARY KEY(ID)
)ENGINE=InnoBD;

CREATE TABLE REGISTRO (
	ID_J INT,
	ID_P INT,
	PUNTOS INT,
	FOREIGN KEY (ID_J) REFERENCES JUGADOR(ID),
	FOREIGN KEY (ID_P) REFERENCES PARTIDA(ID)
)ENGINE=InnoDB;


INSERT INTO JUGADOR VALUES (1,'DAVID','1234')
INSERT INTO JUGADOR VALUES (2,'CLAUDIA','ABC')
INSERT INTO JUGADOR VALUES (3,'POL','12AB')



INSERT INTO PARTIDA VALUES (1,'11/13/9/2021','25','DAVID')
INSERT INTO PARTIDA VALUES (2,'17/10/10/2021','18','DAVID')
INSERT INTO PARTIDA VALUES (1,'19/2/2/2022','40','DAVID')


INSERT INTO REGISTRO VALUES (1,1,1)
INSERT INTO REGISTRO VALUES (2,1,0)
INSERT INTO REGISTRO VALUES (1,2,1)
INSERT INTO REGISTRO VALUES (3,2,0)
INSERT INTO REGISTRO VALUES (1,3,0)
INSERT INTO REGISTRO VALUES (2,3,1)
INSERT INTO REGISTRO VALUES (3,3,0)
